### ISSUE TITLE
Crash upon opening app

### ISSUE THREAD

**Issue by LaurensVanDenberghe** [rsyncOSX/RsyncOSXsched#259]
`Process:               RsyncOSXsched [4678]
Path:                  /Applications/RsyncOSXsched.app/Contents/MacOS/RsyncOSXsched
Identifier:            no.blogspot.RsyncOSXsched
Version:               6.1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RsyncOSXsched [4678]
User ID:               502

Date/Time:             2020-01-03 13:15:13.629 +0100
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Anonymous UUID:        C2FCFD1F-8982-1ED7-794B-25FB9A6F416E

Time Awake Since Boot: 1300000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [4678]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   no.blogspot.RsyncOSXsched     	0x000000010b891b63 0x10b855000 + 248675
1   no.blogspot.RsyncOSXsched     	0x000000010b880f14 0x10b855000 + 179988
2   no.blogspot.RsyncOSXsched     	0x000000010b894ee9 0x10b855000 + 261865
3   libdispatch.dylib             	0x00007fff6b78e583 _dispatch_call_block_and_release + 12
4   libdispatch.dylib             	0x00007fff6b78f50e _dispatch_client_callout + 8
5   libdispatch.dylib             	0x00007fff6b79abc4 _dispatch_main_queue_callback_4CF + 1105
6   com.apple.CoreFoundation      	0x00007fff342b49a5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
7   com.apple.CoreFoundation      	0x00007fff342746fd __CFRunLoopRun + 2384
8   com.apple.CoreFoundation      	0x00007fff34273738 CFRunLoopRunSpecific + 503
9   com.apple.HIToolbox           	0x00007fff32dba65d RunCurrentEventLoopInMode + 292
10  com.apple.HIToolbox           	0x00007fff32dba39d ReceiveNextEventCommon + 600
11  com.apple.HIToolbox           	0x00007fff32dba127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
12  com.apple.AppKit              	0x00007fff3142beb4 _DPSNextEvent + 990
13  com.apple.AppKit              	0x00007fff3142a690 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
14  com.apple.AppKit              	0x00007fff3141c3ae -[NSApplication run] + 658
15  com.apple.AppKit              	0x00007fff313ee775 NSApplicationMain + 777
16  no.blogspot.RsyncOSXsched     	0x000000010b8580b9 0x10b855000 + 12473
17  libdyld.dylib                 	0x00007fff6b7e87fd start + 1

**Comment by rsyncOSX** [comment]
Hi, It is hard to say why.. There might be some problems with the config files.. The log does not give me info to solve it. If you provide me with your config files I will check if there are any issues regarding loading the schedules..
